[build]
  command = "npm run build"
  publish = "dist"

[dev]
  framework = "astro"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Force HTTPS
[[redirects]]
  from = "http://:domain/*"
  to = "https://:domain/:splat"
  status = 301
  force = true

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200